apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  namespace: default
  labels:
    app: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:  # This should not be null
      containers:
        - name: url-shortener
          image: url-shortener:latest
          command: ["uvicorn"]
          args: ["main:app", "--host", "0.0.0.0", "--port", "8080"]
